spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Development/h2/databases/spring-jpa2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
#            bind: trace